from .models import SourceRecord
from .parsing import chunks,author_year,first_sentences
CONCEPTS=("caste","jati","varna","caste structure","caste relations","caste-class","land relations","agrarian relations","agrarian structure","agrarian transformation","agrarian change","production relations","mode of production","commons","common property","common-pool resources","commoning","enclosure","social boycott","exclusion","Dalit assertion","resistance","village institution","social reproduction")
SECTIONS={"LAND AND CASTE RELATIONS IN INDIA":("caste","land","agrarian","class"),"COMMONS AND CASTE":("commons","commoning","common property","access","governance"),"CONCEPTUALISING SOCIAL BOYCOTT":("social boycott","boycott","exclusion","collective punishment"),"LAND STRUGGLES IN PUNJAB":("Punjab","shamlat","panchayat","land struggle","Dalit")}
def extract_source(text,source_id,title=""):
 author,year=author_year(text);low=text.lower();concepts=[c for c in CONCEPTS if c.lower() in low];geos=[g for g in ("Punjab","Malwa","India","Tamil Nadu","Andhra Pradesh","Odisha","Vidarbha","Uttar Pradesh") if g.lower() in low]
 periods=[p for p,ts in {"ANCIENT":("ancient","early india"),"MEDIEVAL":("medieval","precolonial"),"COLONIAL":("colonial","british"),"POSTCOLONIAL":("post-independence","postcolonial"),"CONTEMPORARY":("contemporary","present","recent")}.items() if any(t in low for t in ts)]
 sections=[s for s,ts in SECTIONS.items() if any(t.lower() in low for t in ts)]
 r=SourceRecord(source_id=source_id,author=author,year=year,title=title,geography=", ".join(geos),historical_period=", ".join(periods),concepts=concepts,literature_sections=sections,main_argument=" ".join(first_sentences(text,("argue","argues","argument","thesis","suggests","finds","shows"),3)),empirical_evidence=first_sentences(text,("evidence","data","interview","survey","ethnograph","case study","documents","finds","found")),mechanisms=first_sentences(text,("mechanism","through which","because","mediates","produces","reproduces","enforces","excludes")),explicit_gap=" ".join(first_sentences(text,("gap","underexplored","unexplored","little is known","remains unclear","limited attention"),2)),limitations=first_sentences(text,("limitation","limit","caveat","cannot","does not"),4),uncertain_fields=["publication","discipline","methodology","exact definitions"])
 r.evidence=[{"source_id":source_id,"page":c["page"],"snippet":c["text"][:700],"evidence_level":"A"} for c in chunks(text)[:30] if c["text"]];return r
